import type { MockCatalogProduct } from "./types.ts";

// All names, brands, descriptions, prices, and availability are synthetic examples.
export const mockCatalogProducts: readonly MockCatalogProduct[] = [
  {
    id: "mock-top-001",
    name: "MOCK: Harbor Linen Shirt",
    category: "tops",
    brand: "Sample Atelier",
    description: "Synthetic relaxed-fit linen-blend shirt for warm days.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["white", "sand"],
    occasions: ["casual", "work", "travel"],
    source: "mock",
    price: { amount: 42, currency: "USD", isMock: true },
    availability: { status: "mock-only", note: "No live inventory is connected." },
  },
  {
    id: "mock-top-002",
    name: "MOCK: Cloudline Overshirt",
    category: "tops",
    brand: "Example Works",
    description: "Synthetic midweight overshirt with a roomy shape for layering.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["olive", "tan"],
    occasions: ["casual", "travel", "outdoor"],
    source: "mock",
    price: { amount: 58, currency: "USD", isMock: true },
    availability: { status: "mock-only", note: "No live inventory is connected." },
  },
  {
    id: "mock-bottom-001",
    name: "MOCK: Everyday Straight-Leg Trouser",
    category: "bottoms",
    brand: "Sample Atelier",
    description: "Synthetic straight-leg trouser intended for everyday outfits.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["charcoal", "navy"],
    occasions: ["casual", "work"],
    source: "mock",
    price: { amount: 64, currency: "USD", isMock: true },
    availability: { status: "mock-only", note: "No live inventory is connected." },
  },
  {
    id: "mock-dress-001",
    name: "MOCK: Studio Knit Dress",
    category: "dresses",
    brand: "Example Works",
    description: "Synthetic soft-knit midi dress with a simple silhouette.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["black", "burgundy"],
    occasions: ["work", "evening"],
    source: "mock",
    price: { amount: 85, currency: "USD", isMock: true },
    availability: { status: "mock-only", note: "No live inventory is connected." },
  },
  {
    id: "mock-footwear-001",
    name: "MOCK: Weekend Canvas Sneaker",
    category: "footwear",
    brand: "Demo Footwear Co.",
    description: "Synthetic low-top canvas sneaker for casual outfits.",
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    colors: ["white", "navy"],
    occasions: ["casual", "travel"],
    source: "mock",
    price: { amount: 64, currency: "USD", isMock: true },
    availability: { status: "mock-only", note: "No live inventory is connected." },
  },
  {
    id: "mock-outerwear-001",
    name: "MOCK: Trail Utility Jacket",
    category: "outerwear",
    brand: "Demo Field Goods",
    description: "Synthetic lightweight utility jacket with roomy pockets.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["forest", "black"],
    occasions: ["outdoor", "travel"],
    source: "mock",
    price: { amount: 110, currency: "USD", isMock: true },
    availability: { status: "mock-only", note: "No live inventory is connected." },
  },
];
